"""Licensing constants: key format, grace window, endpoints, retry policy."""

from __future__ import annotations

LICENSE_PREFIX = "ATK"
LICENSE_PAYLOAD_LENGTH = 20
LICENSE_GROUP_LENGTH = 5
LICENSE_GROUP_COUNT = 4
LICENSE_KEY_LENGTH = LICENSE_PAYLOAD_LENGTH + 1  # payload + checksum

LICENSE_ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"
LICENSE_CHECKSUM_MODULUS = 37
LICENSE_CHECKSUM_BASE = 37

DEFAULT_GRACE_DAYS = 7
DEFAULT_VALIDATION_INTERVAL_SECONDS = 6 * 60 * 60

DEFAULT_REQUEST_TIMEOUT = 10.0
DEFAULT_MAX_RETRIES = 3
DEFAULT_BACKOFF_SECONDS = 0.5
DEFAULT_MAX_BACKOFF_SECONDS = 4.0

# Public-key resolution (verification only; the private key stays server-side).
LICENSE_PUBLIC_KEY_ENV_VAR = "AUTOTUBE_LICENSE_PUBLIC_KEY"
LICENSE_PUBLIC_KEY_FILE_ENV_VAR = "AUTOTUBE_LICENSE_PUBLIC_KEY_FILE"
BUNDLED_PUBLIC_KEY_FILE_NAME = "license_public.pem"
