"""Centralized, phase-shared constants for AutoTube Creator.

Media-specific constants live in :mod:`autotube.media.constants`. This module
holds values shared by models, config, and the media layer so render defaults
have a single source of truth.
"""

from __future__ import annotations

DEFAULT_RESOLUTION = "1920x1080"
DEFAULT_FPS = 30
DEFAULT_MUSIC_VOLUME = 0.2
DEFAULT_WHISPER_MODEL = "base"
DEFAULT_CAPTION_STYLE = "burned"
DEFAULT_LOG_LEVEL = "INFO"

DEFAULT_MIN_SEGMENT_DURATION = 1.0
DEFAULT_MAX_SEGMENT_DURATION = 8.0
DEFAULT_MERGE_GAP_THRESHOLD = 0.25
DEFAULT_VAD_FILTER = True

DEFAULT_STOCK_TIMEOUT = 15.0
DEFAULT_STOCK_MAX_RETRIES = 3
DEFAULT_STOCK_MAX_KEYWORDS = 4
DEFAULT_STOCK_MIN_RESOLUTION = "1280x720"

STOCK_PROVIDER_PEXELS = "pexels"
STOCK_PROVIDER_PIXABAY = "pixabay"
PEXELS_API_KEY_ENV_VAR = "PEXELS_API_KEY"
PIXABAY_API_KEY_ENV_VAR = "PIXABAY_API_KEY"
DEFAULT_STOCK_PROVIDERS = (STOCK_PROVIDER_PEXELS, STOCK_PROVIDER_PIXABAY)

DEFAULT_AI_ENABLED = False
DEFAULT_AI_PROVIDER = "openai_compatible"
DEFAULT_AI_MODEL = "deepseek/deepseek-v4-flash-0731"
DEFAULT_AI_API_KEY_ENV_VAR = "OPENROUTER_API_KEY"
DEFAULT_AI_BASE_URL = "https://openrouter.ai/api/v1/chat/completions"

LEGACY_AI_MODEL = "deepseek/deepseek-v4-flash"
LEGACY_AI_API_KEY_ENV_VAR = "COMMAND_CODE_API_KEY"
LEGACY_AI_BASE_URL = "https://api.commandcode.ai/provider/v1/chat/completions"

AI_PROVIDER_OPENROUTER = "openai_compatible"
AI_PROVIDER_DASHSCOPE = "dashscope"
DASHSCOPE_DEFAULT_MODEL = "qwen3.7-plus"
DASHSCOPE_DEFAULT_BASE_URL = (
    "https://dashscope-intl.aliyuncs.com/compatible-mode/v1/chat/completions"
)
DASHSCOPE_API_KEY_ENV_VAR = "DASHSCOPE_API_KEY"
DASHSCOPE_DISPLAY_NAME = "Alibaba Cloud DashScope"

DEFAULT_AI_TEMPERATURE = 0.2
DEFAULT_AI_MAX_KEYWORDS = 6
DEFAULT_AI_BATCH_SIZE = 8
DEFAULT_AI_MAX_INPUT_CHARS = 6000
DEFAULT_AI_MAX_KEYWORD_CHARS = 80
DEFAULT_AI_TIMEOUT = 30.0
DEFAULT_AI_MAX_RETRIES = 3
DEFAULT_AI_MAX_BACKOFF_SECONDS = 8.0

DEFAULT_AI_IMAGE_ENABLED = False
DEFAULT_AI_IMAGE_PROVIDER = ""
DEFAULT_AI_IMAGE_MODEL = ""
DEFAULT_AI_IMAGE_API_KEY_ENV_VAR = ""
DEFAULT_AI_IMAGE_BASE_URL = ""
DEFAULT_AI_IMAGE_TIMEOUT = 60.0

DEFAULT_AI_VIDEO_ENABLED = False
DEFAULT_AI_VIDEO_PROVIDER = ""
DEFAULT_AI_VIDEO_MODEL = ""
DEFAULT_AI_VIDEO_API_KEY_ENV_VAR = ""
DEFAULT_AI_VIDEO_BASE_URL = ""
DEFAULT_AI_VIDEO_TIMEOUT = 120.0

DEFAULT_TRANSITION_DURATION = 1.0
DEFAULT_TRANSITION_EFFECT = "fade"
DEFAULT_TRANSITION_SOUND_VOLUME = 0.35
SUPPORTED_TRANSITION_SOUND_EXTENSIONS = {
    ".mp3",
    ".wav",
    ".m4a",
    ".aac",
    ".flac",
    ".ogg",
}
